
backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "gallery"
    label: "גלריה"
    folder: "gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "שם תמונה", name: "title", widget: "string"}
      - {label: "תמונה", name: "image", widget: "image"}
